

   MP15NumAmbosMoto = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P15_8_Moto",fTlevels = T,fbanner = bandera1),
   MP15UsoAmbosMoto = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = nombresR(datos,"Rr_P15_9_MOTO"),fTlevels = F,fbanner = bandera1),
   MP15MarcaAmbosMoto = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = nombresR(datos,"P15_6_MARCA_AMBOS"),fTlevels = T,fbanner = bandera1),
   MP15AmbosCategoriaMoto = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = nombresR(datos,"P15_6_CATEGORIA_AMBOS"),fTlevels = T,fbanner = bandera1),
   MP15AntAmbosMoto = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = nombresR(datos,"P15_7_AMBOS"),fTlevels = T,fbanner = bandera1),
   MP17PrestarAmbosMotos = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_A_AMBOS",fTlevels = T,fbanner = bandera1),
   MP17PrestarQuienAmbosMotos = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")),],fTvariables =nombresR(datos,"P17_B_AMBOS"),fTlevels = F,fbanner = bandera1),
   MP17PrestarQuienAmbosMotosf1 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")&(datos$P17_B_AMBOS_Mi_Esposo___Esposa=="TRUE")),],fTvariables ="P17_C_AMBOS_ESPOSAESPOSO",fTlevels = T,fbanner = bandera1),
   MP17PrestarQuienAmbosMotosf2 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")&(datos$P17_B_AMBOS_Mi_Pap____Mam=="TRUE")),],fTvariables ="P17_C_AMBOS_MAMAPAPA",fTlevels = T,fbanner = bandera1),
   MP17PrestarQuienAmbosMotosf3 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")&(datos$P17_B_AMBOS_Hijos___Hijas=="TRUE")),],fTvariables ="P17_C_AMBOS_HIJOHIJA",fTlevels = T,fbanner = bandera1),
   MP17PrestarQuienAmbosMotosf4 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")&(datos$P17_B_AMBOS_Otro_familiar=="TRUE")),],fTvariables ="P17_C_AMBOS_OTROFAMILIAR",fTlevels = T,fbanner = bandera1),
   MP17AmbosPrestarQuienMotosRazon1 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")&(datos$P17_B_AMBOS_Mi_Esposo___Esposa=="TRUE")),],fTvariables = nombresR(datos,"P17_D_AMBOS_ESPOSAESPOSO")[1:12],fTlevels = F,fbanner = bandera1),
   MP17AmbosPrestarQuienMotosRazon2 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")&(datos$P17_B_AMBOS_Mi_Pap____Mam=="TRUE")),],fTvariables =nombresR(datos,"P17_D_AMBOS_MAMAPA")[1:12],fTlevels = F,fbanner = bandera1),
   MP17AmbosPrestarQuienMotosRazon3 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")&(datos$P17_B_AMBOS_Hijos___Hijas=="TRUE")),],fTvariables =nombresR(datos,"P17_D_AMBOS_HIJOHIJA")[1:12],fTlevels = F,fbanner = bandera1),
   MP17AmbosPrestarQuienMotosRazon4 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "Sí")&(datos$P17_B_AMBOS_Otro_familiar=="TRUE")),],fTvariables =nombresR(datos,"P17_D_AMBOS_OTROFAMILIAR")[1:12],fTlevels = F,fbanner = bandera1),
   MP17NoPrestaMotosPQ = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "No")),],fTvariables ="P17_E_AMBOS",fTlevels = T,fbanner = bandera1), 
   MP17NoPrestaMotosProb = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "No")),],fTvariables ="P17_F",fTlevels = T,fbanner = bandera1),
   MP17NoPrestaMotosProbQ = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "No")&(datos$P17_F== 'Sí')),],fTvariables ="P17_G_AMBOS",fTlevels = T,fbanner = bandera1),
   MP17NoPrestarQuienMotosSol1 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "No")&(datos$P17_G=="Esposa/ Esposo")),],fTvariables = "P17_H_AMBOS_ESPOSAESPOSO",fTlevels = T,fbanner = bandera1),
   MP17NoPrestarQuienMotosSol2 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "No")&(datos$P17_G=="Mamá/ Papá")),],fTvariables = "P17_H_AMBOS_PAPAMAMA",fTlevels = T,fbanner = bandera1),
   MP17NoPrestarQuienMotosSol3 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "No")&(datos$P17_G=="Hijo/hija")),],fTvariables = "P17_H_AMBOS_HIJOHIJA",fTlevels = T,fbanner = bandera1),
   MP17NoPrestarQuienMotosSol4 = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P17_A_AMBOS== "No")&(datos$P17_G=="Otro familiar")),],fTvariables = "P17_H_AMBOS_OTROFAMILIAR",fTlevels = T,fbanner = bandera1),
   MP17Actividades1 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_ir_a_trabajar",fTlevels = T,fbanner = bandera3),
   MP17Actividades2 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_ir_al_Doctor___Den",fTlevels = T,fbanner = bandera3),
   MP17Actividades3 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_llevar_hijos_a_la_",fTlevels = T,fbanner = bandera3),
   MP17Actividades4 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_salir_de_paseo___s",fTlevels = T,fbanner = bandera3),
   MP17Actividades5 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_salir_de_vacacione",fTlevels = T,fbanner = bandera3),
   MP17Actividades6 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_llevar___transport",fTlevels = T,fbanner = bandera3),
   MP17Actividades7 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_salir_de_fiesta",fTlevels = T,fbanner = bandera3),
   MP17Actividades8 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_ir_al_s_per___merc",fTlevels = T,fbanner = bandera3),
   MP17Actividades9 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_ir_al_banco",fTlevels = T,fbanner = bandera3),
   MP17Actividades10 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_ir_a_la_Escuela___",fTlevels = T,fbanner = bandera3),
   MP17Actividades11 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_ir_a_visitar_a_mi_",fTlevels = T,fbanner = bandera3),
   MP17Actividades12 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_J_AMBOS_La_uso_para_salir_a_las_rodada",fTlevels = T,fbanner = bandera3),
   MAP17Preferencia = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P17_K_AMBOS",fTlevels = T,fbanner = bandera1),
   MAP17PREFERENCIAMOTOS= frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables =nombresR(datos,"P17_M_AMBOS")[1:7],fTlevels = F,fbanner = bandera1),
   MP16InfluenciaMotos = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables =nombresR(datos,"P17_O_")[c(2,4,6,8,10,12)],fTlevels = F,fbanner = bandera1),
   MP16CompraMotos = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = nombresR(datos,"P17_P_")[c(2,4,6,8,10,12,14)],fTlevels = F,fbanner = bandera1),
   MP18 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables ="P18_AMBOS_Moto",fTlevels = T,fbanner = bandera1),
   MP18Cambio = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = nombresR(datos,"P18_A_Ambos_")[c(2,4,6,8,10,12,14,16,18,20,22,24)],fTlevels = F,fbanner = bandera1),
   MP18TransporteEficiente = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables ="P18_B_AMBOS",fTlevels = T,fbanner = bandera1),
   MP18C1 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P18_D_AMBOS_Me_da_prestigio___status",fTlevels = T,fbanner = bandera1),
   MP18C2 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P18_D_AMBOS_Me_da_tranquilidad",fTlevels = T,fbanner = bandera1),
   MP18C3 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P18_D_AMBOS_Me_da_confianza",fTlevels = T,fbanner = bandera1),
   MP18C4 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P18_D_AMBOS_Me_da_seguridad",fTlevels = T,fbanner = bandera1),
   MP18C5 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables = "P18_D_AMBOS_Me_siento_contento__a",fTlevels = T,fbanner = bandera1),
   MP19 = frecuentator(fTtabla = datos[datos$P10=="Ambas",],fTvariables ="P19_C_AMBOS",fTlevels = T,fbanner = bandera1),
   MP19A = frecuentator(fTtabla = datos[((datos$P10=="Ambas")& (datos$P19_C_AMBOS== "Es usada")),],fTvariables ="P19_D_AMBOS",fTlevels = T,fbanner = bandera1),
   MP19B = frecuentator(fTtabla = datos[(datos$P10=="Ambas"),],fTvariables =(nombresR(datos,"P19_E_")[1:6]),fTlevels = F,fbanner = bandera1),
   MP19BBanco1 = frecuentator(fTtabla = datos[((datos$P10=="Ambas") & (datos$P19_E_AMBOS_Tarjeta_de_Cr_dito=="TRUE")),],fTvariables ="P20_e_bancor",fTlevels = T,fbanner = bandera1),
   MP19BBanco2 = frecuentator(fTtabla = datos[((datos$P10=="Ambas") & (datos$P19_E_AMBOS_Cr_dito_personal_del_banco=="TRUE")),],fTvariables ="P20_e_bancor",fTlevels = T,fbanner = bandera1),
   MP19BBanco3 = frecuentator(fTtabla = datos[((datos$P10=="Ambas") & (datos$P19_E_AMBOS_Otro__Especificar=="TRUE")),],fTvariables ="P20_e_bancor",fTlevels = T,fbanner = bandera1),
   MP19BBanco4 = frecuentator(fTtabla = datos[((datos$P10=="Ambas") & (datos$P19_E_AMBOS_No_sabe__no_contest=="TRUE")),],fTvariables ="P20_e_bancor",fTlevels = T,fbanner = bandera1),
   MP19E1  = frecuentator(fTtabla = datos[datos$P10=="Ambas",], fTvariables = nombresR(datos,"P19_E_1")[1:4],fTlevels = F,fbanner = bandera1),
   MP20 = frecuentator(fTtabla = datos[datos$P10=="Ambas",], fTvariables = "P20_F",fTlevels = T,fbanner = bandera1),
   MP20H  = frecuentator(fTtabla = datos[((datos$P10=="Ambas") & (datos$P20_F=="Si")),], fTvariables = "P20_H_AMBOS",fTlevels = T,fbanner = bandera1),
   #MP18C = frecuentator(fTtabla = datos[((datos$P10=="Ambas") & (datos$P20_F=="Si")),],fTvariables =(nombresR(datos,"P20_I_AMBOS")[1:6]),fTlevels = F,fbanner = bandera1),
   MAp18E = frecuentator(fTtabla = datos[datos$P10=="Ambas" & datos$P20=="Si",], fTvariables =nombresR(datos,"P20_J_")[1:10],fTlevels = F,fbanner = bandera1),
   MAMP20F1 = frecuentator(fTtabla = datos[datos$P10=="Ambas" & datos$P20=="Si" & datos$P20_J_AMBOS_Italika=="TRUE",], fTvariables =nombresR(datos,"P20_K_")[1:15],fTlevels = F,fbanner = bandera1),
   MAMP20F2 = frecuentator(fTtabla = datos[datos$P10=="Ambas" & datos$P20=="Si" & datos$P20_J_AMBOS_Yamaha=="TRUE",], fTvariables =nombresR(datos,"P20_K_")[17:31],fTlevels = F,fbanner = bandera1),
   MAMP20F3 = frecuentator(fTtabla = datos[datos$P10=="Ambas" & datos$P20=="Si" & datos$P20_J_AMBOS_Honda=="TRUE",], fTvariables =nombresR(datos,"P20_K_")[33:47],fTlevels = F,fbanner = bandera1),
   MAMP20F4 = frecuentator(fTtabla = datos[datos$P10=="Ambas" & datos$P20=="Si" & datos$P20_J_AMBOS_Suzuki=="TRUE",], fTvariables =nombresR(datos,"P20_K_")[49:63],fTlevels = F,fbanner = bandera1),
   MAMP20F5 = frecuentator(fTtabla = datos[datos$P10=="Ambas" & datos$P20=="Si" & datos$P20_J_AMBOS_Bajaj=="TRUE",], fTvariables =nombresR(datos,"P20_K_")[65:79],fTlevels = F,fbanner = bandera1),
   MAMP20F6 = frecuentator(fTtabla = datos[datos$P10=="Ambas" & datos$P20=="Si" & datos$P20_J_AMBOS_Kawasaki=="TRUE",], fTvariables =nombresR(datos,"P20_K_")[81:95],fTlevels = F,fbanner = bandera1),
   MAMP20F7 = frecuentator(fTtabla = datos[datos$P10=="Ambas" & datos$P20=="Si" & datos$P20_J_AMBOS_Harley_Davidson=="TRUE",], fTvariables =nombresR(datos,"P20_K_")[97 :111],fTlevels = F,fbanner = bandera1)
   
   
   
   
   table(datos$P15_4)
   table(datos$P15_4_1) 
   table(datos$P15_11)
   table(datos$P15_11_1)
   
